# version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: chat-app-nest
    # command: npm run start:dev
    command: ["./wait-for-it.sh", "rabbitmq:5672", "--", "npm", "run", "start:dev"]
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - mongo
      - rabbitmq
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:5
    container_name: chat-app-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: chat-app-rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

volumes:
  mongo-data: