FROM node:18

WORKDIR /app

COPY package*.json ./

# Salin wait-for-it.sh ke dalam kontainer
COPY wait-for-it.sh /wait-for-it.sh

RUN chmod +x /wait-for-it.sh

RUN npm install

COPY . .

EXPOSE 3000

# CMD [ "npm", "run",  "start:dev"]
# CMD /wait-for-it.sh rabbitmq:5672 -- npm run start:dev
CMD ["/wait-for-it.sh", "rabbitmq:5672", "--", "npm", "run", "start:dev"]


# RUN npm run build
# CMD [ "npm", "run",  "start:prod"]